version: '3.8'

services:
  streamlit-app:
    build:
      context: .  # Diretório onde o Dockerfile está localizado
    ports:
      - "8502:8502"  # Mapeia a porta 8502 do container para a porta 8502 da máquina host
    volumes:
      - .:/app  # Monta o diretório atual no container para facilitar o desenvolvimento
    environment:
      - PYTHONUNBUFFERED=1  # Garante que a saída do Python seja exibida em tempo real
